server:
  port: 53763
spring:
  application:
    name: MultiTenant
  datasource:
    url: jdbc:h2:mem:MultiTenant
    driverClassName: org.h2.Driver
  h2:
   console:
      enabled: true
      path: /h2
  main:
    allow-circular-references: true
  jpa:
    database-platform: 
      org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: create